### PR TITLE
tests passed successfully

### PR DESCRIPTION
**Pull request by Spyros-Av**

### CODE REVIEW

**Review by stacon — COMMENTED** [review]
Everything looks fine but I'd suggest that functions like isRoyalFlush etc, should take a unordered hand as input. If you are planning to do this in a future iteration then I'll approve this pr when you are ready. Also you should pull develop in your current branch and resolve the conflicts cause by the PR. If you need help, ping me!

**Comment by Spyros-Av** [comment]
> Everything looks fine but I'd suggest that functions like isRoyalFlush etc, should take a unordered hand as input. If you are planning to do this in a future iteration then I'll approve this pr when you are ready. Also you should pull develop in your current branch and resolve the conflicts cause by the PR. If you need help, ping me!

To tell you the truth i didn't exactly understand what you mean about the input I should have to my functions.
I resolved the conflicts and pushed the latest version.

**Comment by stacon** [comment]
> > Everything looks fine but I'd suggest that functions like isRoyalFlush etc, should take a unordered hand as input. If you are planning to do this in a future iteration then I'll approve this pr when you are ready. Also you should pull develop in your current branch and resolve the conflicts cause by the PR. If you need help, ping me!
> 
> To tell you the truth i didn't exactly understand what you mean about the input I should have to my functions.
> I resolved the conflicts and pushed the latest version.

It would be nice if you can take a random hand and send it to each of these functions. For example `isRoyalFlush(cards)` and the sorting and all the other operations needed can be done inside them. Think that the purposes is that these functions should be able to recognize if are truthy or faulty with no pre-procession. Call me if you need definitions on this.

**Comment by Spyros-Av** [comment]
> > > Everything looks fine but I'd suggest that functions like isRoyalFlush etc, should take a unordered hand as input. If you are planning to do this in a future iteration then I'll approve this pr when you are ready. Also you should pull develop in your current branch and resolve the conflicts cause by the PR. If you need help, ping me!
> > 
> > 
> > To tell you the truth i didn't exactly understand what you mean about the input I should have to my functions.
> > I resolved the conflicts and pushed the latest version.
> 
> It would be nice if you can take a random hand and send it to each of these functions. For example `isRoyalFlush(cards)` and the sorting and all the other operations needed can be done inside them. Think that the purposes is that these functions should be able to recognize if are truthy or faulty with no pre-procession. Call me if you need definitions on this.

I see. Ok, I will try to implement it the way you told me then.

**Review by stacon — APPROVED** [review]
Good job man!

**Pull request merged**
